# Generated by Django 4.2.13 on 2026-07-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='fa-car', help_text='FontAwesome icon class e.g. fa-car, fa-motorcycle', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Hyundai Creta, Royal Enfield Classic 350', max_length=100)),
                ('brand', models.CharField(help_text='e.g., Hyundai, Tata, Mahindra, Honda', max_length=50)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike / Scooter')], default='CAR', max_length=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, help_text='Rental price per 24 hours in INR', max_digits=10)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=150, help_text='Hourly rate', max_digits=10)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('CNG', 'CNG')], default='Petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=20)),
                ('seats', models.PositiveIntegerField(default=5)),
                ('mileage', models.CharField(default='18 kmpl', max_length=30)),
                ('year', models.PositiveIntegerField(default=2023)),
                ('location', models.CharField(default='Morbi', help_text='Pickup location', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL if direct file upload is empty', max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=12)),
                ('features', models.CharField(default='GPS, Bluetooth, AC, Airbags, Reverse Camera', help_text='Comma separated features', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.category')),
            ],
        ),
    ]
