# Generated by Django 6.0.7 on 2026-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='allow_hourly_rental',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='discount_30day_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Discount % for 30+ days', max_digits=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='discount_3day_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Discount % for 3+ days', max_digits=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='discount_7day_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Discount % for 7+ days', max_digits=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='weekend_surge_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Percentage surge for Saturday/Sunday', max_digits=5),
        ),
    ]
