# Generated by Django 6.0.7 on 2026-09-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_allow_hourly_rental_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='allow_hourly_rental',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='discount_30day_percent',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='discount_3day_percent',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='discount_7day_percent',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='weekend_surge_percent',
        ),
    ]
