# Generated by Django 6.1 on 2026-08-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='aadhaar_doc',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/kyc/aadhaar/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='aadhaar_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driving_license_doc',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/kyc/dl/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='driving_license_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(max_length=10),
        ),
    ]
