# Generated by Django 6.1 on 2026-09-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_aadhaar_doc_booking_aadhaar_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='Razorpay / Online UPI', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid / Pending Checkout'), ('PAID', 'Paid - Booking Confirmed'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Fully Refunded')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='security_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='Refundable security deposit amount in INR', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='security_deposit_refund_status',
            field=models.CharField(choices=[('HELD', 'Security Deposit Held in Escrow'), ('REFUND_PENDING', 'Deposit Refund Initiated'), ('REFUNDED', 'Deposit Refunded to Customer'), ('FORFEITED', 'Deposit Forfeited (Vehicle Damage / Penalty)')], default='HELD', max_length=25),
        ),
    ]
