# Generated by Django 6.0.7 on 2026-09-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_paid_at_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='security_deposit_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='security_deposit_refund_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('HELD', 'Security Deposit Held'), ('RELEASED', 'Refund Released'), ('DEDUCTED', 'Deducted for Damage/Late')], default='HELD', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='Refundable Security Deposit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid & Confirmed'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Security Deposit Refunded')], default='UNPAID', max_length=20),
        ),
    ]
