# Generated by Django 6.0.7 on 2026-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('HOURLY', 'Hourly')], default='DAILY', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='surge_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
