# Generated by Django 6.0.7 on 2026-09-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_base_price_booking_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rental_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='surge_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_hours',
        ),
    ]
